[project]
name = "ucas-login"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nemowang", email = "nemowang@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "requests>=2.32.5",
    "xxtea-py>=1.0.3",
]

[project.scripts]
ucas = "ucas_login:main"

[build-system]
requires = ["uv_build>=0.9.11,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
