[project]
name = "ucas-portal"
version = "0.3.0"
description = "中国科学院大学 (UCAS) 校园网 Portal 认证命令行工具"
readme = "README.md"
authors = [
    { name = "nemowang", email = "nemowang@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "requests>=2.32.5",
]

[project.scripts]
ucas-portal = "ucas_portal:main"

[build-system]
requires = ["uv_build>=0.9.11,<0.10.0"]
build-backend = "uv_build"

[tool.ruff]
target-version = "py314"
line-length = 100

[tool.ruff.lint]
extend-ignore = ["E501"]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
]

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
